"""add_payment_fields_to_orders

Revision ID: 37aa096ec2d4
Revises: 1ca94360e803
Create Date: 2026-07-19 16:08:09.854637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37aa096ec2d4'
down_revision: Union[str, Sequence[str], None] = '1ca94360e803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('cash_tendered', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('change_due', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'change_due')
    op.drop_column('orders', 'cash_tendered')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
